# Use an official Python runtime as a parent image
FROM python:3.10.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY /requirements.txt /app/requirements.txt

# Install Jupyter and other dependencies
RUN pip install --no-cache-dir numpy scikit-learn rasterio geopy geopandas shapely pandas geojson tqdm matplotlib jupyter

# Copy the src directory contents into the container at /app/src
COPY src /app

# Start a terminal session
CMD ["bash"]